[package]
name = "toy_browser_engine"
version = "0.1.0"
authors = ["jpaumier <jpaumier@graimatterlabs.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.105.0"
find_folder = "0.3.0"
